### ISSUE TITLE
Cursorline defaults to background

### ISSUE THREAD

**Issue by epbuennig** [CptPotato/helix-themes#2]
With the release of `helix 22.08` come `ui.cursorline.{primary,secondary}` as keys for themes, recently most of the new keys were added, but not those.

Currently, the cursor line doesn't show up at all, if enabled, as it defaults to the background color.

I propose adding the following to at least `schemes/gruvbox`, but possibly all schemes:
```toml
"ui.cursorline.primary" = { bg = "bg1" }
"ui.cursorline.secondary" = { bg = "bg1" }
```
I also tried it with `bg3`, which drowned out the whitespace characters and felt a bit on the nose for a passive thing like that.
Example using `bg1` in `gruvbox_original_dark_hard`:
![image](https://user-images.githubusercontent.com/103939966/188693010-b81bdd1d-873c-4d4d-916c-3ce27015e924.png)
